# Generated by Django 4.2.5 on 2023-10-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_user_plus", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="UserPlus",
        ),
    ]
